export const STOPWORDS = new Set<string>([
  "the","a","an","it","its","they","them","their","i","you","he","she","we","us","our",
    "this","that","these","those","there","here","what","which","who","whom","whose",
    "to","of","in","on","at","by","for","from","with","about","into","over","after","under",
    "and","or","but","so","yet","nor","either","neither","both","not","no",
    "is","am","are","was","were","be","been","being","do","does","did","done",
    "have","has","had","having","can","could","will","would","shall","should","may","might","must",
    "as","than","too","very","just","only","also","if","because","while","since","until","before","between",
    "up","down","out","off","again","further","then","once","each","few","more","most","some","such","own",
    "same","i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself", 
    "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself", 
    "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that", 
    "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", 
    "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because", "as", 
    "until", "while", "of", "at", "by", "for", "with", "about", "against", "between", "into", "through", 
    "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out", "on", "off", 
    "over", "under", "again", "further", "then", "once", "here", "there", "when", "where", "why", "how", 
    "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", 
    "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just", "don", "should", "now"
].map(w => w.toLowerCase()));